version: '3.8'

services:
  planetarium:
    build: .
    env_file: 
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
      - media_volume:/files/media
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U planetarium -d planetarium"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
  media_volume:
